config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  root to: 'posts#index'

  devise_for :users
  resources :posts
  resources :users do
    resources :relationships, only: [:create]
  end
  resources :relationships, only: [:destroy]

  get 'search', to: "users#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :followers, foreign_key: "followed_id", class_name: "Relationship" 
  has_many :following, foreign_key: "follower_id", class_name: "Relationship" 
  has_many :notifications, dependent: :destroy

  validates :username, presence: true, uniqueness: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  scope :search_for, ->(name) { where("lower(username) like '%#{name}%'") }
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  def show
    # @user = User.search_for(params[:name])
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def search
    @searchs = User.search_for(params[:name])
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.users(@user)
    @relation = @user.followers.find_by(follower: current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:user).permit(:username, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Users</h1>

app/views/users/search.html.erb
<h1>Search</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Usuário</th>
      <th scope="col">Ação</th>
    </tr>
  </thead>
  <tbody>
    <% @searchs.each do |user| %>
      <tr scope="row">
        <td><strong><%= user.username %></strong></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Show</h1>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  Followers: <%= @user.followers.count %>
  Following: <%= @user.following.count %>
</p>

<%= link_to 'Back', posts_path, class: "btn btn-secondary" %>
<% if @user.id != current_user.id %>
  <%= 
    link_to 'Follow', user_relationships_path(@user), method: :post, class: "btn btn-danger" unless @relation.present?
  %>
  <%= 
    link_to 'Unfollow', relationship_path(@relation.id), method: :delete, class: "btn btn-danger" if @relation.present?
  %>
<% end %>
<br /><br />

<h3 class="h3">Posts</h3>

<% @posts.each do |post| %>
  <hr>
  <div class="col">
    <strong><%= post.title %></strong>
  </div>
  <div class="col">
    <%= post.body %>
  </div>
<% end %>