config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  root to: 'posts#index'

  devise_for :users
  resources :posts
  resources :users do
    resources :relationships, only: [:create]
  end
  resources :relationships, only: [:destroy]

  get 'search', to: "users#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, :body, presence: true

  scope :users, ->(id) { where( user_id: id ) }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order('created_at DESC')
  end

  # GET /posts/1 or /posts/1.json
  def show

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.text_field :title, class: "form-control", placeholder: "Title..." %>
  </div>

  <div class="mb-3">
    <%= form.text_area :body, class: "form-control", placeholder: "Body..." %>
  </div>

  <div class="actions">
    <%= link_to 'Back', posts_path, class: "btn btn-secondary" %>
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<% @posts.each do |post| %>
  <hr>
  <strong>
    <%= post.user.username %>
  </strong>
  <%= time_ago_in_words(post.created_at.to_date) %>
  <div class="fs-3">
    <%= post.title %>
  </div>
  <div class="fs-4">
    <%= post.body %>
  </div>
  <%= link_to 'Show', post %>
  <% if post.user_id == current_user.id %>
    <%= link_to 'Edit', edit_post_path(post) %>
    <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %> 
  <br>
<% end %>

app/views/posts/new.html.erb
<div class="container">
  <h1 class="h1">New Post</h1>

  <%= render 'form', post: @post %>
</div>

app/views/posts/search.html.erb
<h1>Search</h1>

<div class="container-fluid">
  <% @search.each do |post| %>
    <div class="row">
      <div class="col">
        <strong><%= post.user.username %></strong>
      </div>
      <div class="col-10">
        <%= link_to 'Show', post %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.username %>
</p>

<%= link_to 'Back', posts_path, class: "btn btn-secondary" %>
<% if @post.user_id == current_user.id %>
  <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary" %>
<% end %>