config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  root to: 'posts#index'

  devise_for :users
  resources :posts
  resources :users do
    resources :relationships, only: [:create]
  end
  resources :relationships, only: [:destroy]

  get 'search', to: "users#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>eTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container"
      <div class="container-md">
        <% if user_signed_in? %>
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <%= link_to "Home", root_path, class: "navbar-brand" %>
              <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <%= link_to "New Post", new_post_path, class: "nav-link" %>
                  </li>
                  <li class="nav-item position-relative">
                    <%= link_to "Notification", notifications_path, class: "nav-link" %>
                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                      <%= @notification_unread %>
                    </span>
                  </li>
                </ul>
                <span class="navbar-text">
                  <%= current_user.username %>
                </span>
                <span class="navbar-text">
                  <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "nav-link" %>
                </span>
              </div>
            </div>
            <form class="d-flex" action="/search">
              <input class="form-control me-2" name="name" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </nav>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>